# Generated by Django 5.2.1 on 2025-12-18 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bienvenido a JascShop', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la factura')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final con impuestos y descuentos', max_digits=10)),
                ('metodo_pago', models.CharField(default='No especificado', help_text='Método de pago elegido', max_length=30)),
                ('estado_pago', models.CharField(default='Pendiente', help_text='Estado del pago', max_length=20)),
                ('transaccion_id', models.CharField(blank=True, help_text='ID de transacción del banco/proveedor', max_length=100, null=True)),
                ('banco', models.CharField(blank=True, help_text='Banco usado en el pago si aplica', max_length=100, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario dueño de la factura', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgs/products/')),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Producto destacado en portada')),
                ('nuevo', models.BooleanField(default=False, help_text='Producto marcado como nuevo')),
                ('is_tax_exempt', models.BooleanField(default=False, help_text='Exento de impuestos')),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('talla', models.CharField(blank=True, help_text='Lista separada por comas: S,M,L,XL', max_length=200)),
                ('color', models.CharField(blank=True, help_text='Lista separada por comas: Blanco,Negro,Azul', max_length=200)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/products/')),
                ('video_thumb', models.ImageField(blank=True, null=True, upload_to='imgs/products/video_thumbs/')),
                ('category', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('talla', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='store.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgs/products/gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
