# Generated by Django 5.2.1 on 2025-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad de entrega', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento de entrega', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección de entrega', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre completo del cliente', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=30, null=True),
        ),
    ]
