# Generated by Django 5.2.1 on 2025-11-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_discount_alter_factura_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bienvenido a LatinShop', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
