# Generated by Django 5.2.1 on 2025-11-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_tax_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
