# Generated by Django 5.2.1 on 2025-12-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_factura_ciudad_factura_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_pedido',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', help_text='Estado actual del pedido', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', help_text='Estado del pago', max_length=20),
        ),
    ]
