# Generated by Django 5.2.7 on 2025-11-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
    ]
