# Generated by Django 5.2.7 on 2025-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
