# Generated by Django 5.2.1 on 2025-11-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_tax_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
