# Generated by Django 5.2.1 on 2025-12-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_factura_estado_pedido_alter_factura_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='es_pago_real',
            field=models.BooleanField(default=False, help_text='Indica si el pago fue confirmado por el proveedor o es simulado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_pago',
            field=models.CharField(default='Pendiente', help_text='Estado del pago', max_length=20),
        ),
    ]
