# Generated by Django 5.2.1 on 2025-12-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_factura_es_pago_real_alter_factura_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='correo_enviado',
            field=models.BooleanField(default=False, help_text='Indica si la factura fue enviada por correo al cliente'),
        ),
    ]
