# Generated by Django 5.2.1 on 2025-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Bienvenido a JascShop', max_length=200),
        ),
    ]
