# Generated by Django 5.2.1 on 2025-12-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Lista de colores separados por coma, ej: Blanco,Negro,Azul', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Lista de tallas separadas por coma, ej: S,M,L,XL', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de video externo (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
