# Generated by Django 5.2.1 on 2025-12-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_colors_product_sizes_product_video_url'),
    ]

    operations = [
    ]
