# Generated by Django 5.2.1 on 2025-12-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20251205_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Sube un archivo de video (MP4, WebM, etc.)', null=True, upload_to='videos/products/'),
        ),
    ]
