# Generated by Django 5.2.1 on 2025-12-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Lista de colores separadas por coma, ej: Blanco,Negro,Azul', max_length=200),
        ),
    ]
