# Generated by Django 5.2.1 on 2025-12-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_thumb',
            field=models.ImageField(blank=True, help_text='Miniatura del video para miniatura clicable', null=True, upload_to='imgs/products/video_thumbs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Lista separada por comas: Blanco,Negro,Azul', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Lista separada por comas: S,M,L,XL', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL YouTube/Vimeo/etc.', null=True),
        ),
    ]
