# Generated by Django 5.2.1 on 2025-12-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_video_thumb_alter_product_colors_and_more'),
    ]

    operations = [
    ]
