# Generated by Django 5.2.1 on 2026-01-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20260104_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_vinculado',
            field=models.CharField(blank=True, help_text='Escribe el color exacto (ej: Negro) para que esta foto lo active al hacer clic.', max_length=50, null=True),
        ),
    ]
