# Generated by Django 5.2.1 on 2025-12-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20251206_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
