# Generated by Django 5.2.1 on 2025-12-10 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_detallefactura_color_detallefactura_talla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='Cantidad de unidades compradas'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='color',
            field=models.CharField(blank=True, help_text='Color seleccionado por el cliente', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(help_text='Factura a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='store.factura'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(help_text='Producto comprado', on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal de esta línea (precio unitario * cantidad)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='talla',
            field=models.CharField(blank=True, help_text='Talla seleccionada por el cliente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='banco',
            field=models.CharField(blank=True, help_text='Banco usado en el pago si aplica', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_pago',
            field=models.CharField(default='Pendiente', help_text='Estado del pago (Pendiente, Pagado, Fallido)', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(default='No especificado', help_text='Método de pago elegido (banco, contraentrega, etc.)', max_length=30),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total final de la factura con impuestos y descuentos', max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID de transacción del proveedor de pagos', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario dueño de la factura', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/products/video_thumbs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
