# Generated by Django 5.2.1 on 2026-01-19 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage_color_vinculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible para esta combinación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_stock', to='store.product')),
            ],
            options={
                'verbose_name': 'Variante de Stock',
                'verbose_name_plural': 'Variantes de Stock',
                'unique_together': {('product', 'talla', 'color')},
            },
        ),
    ]
