# Generated by Django 5.2.1 on 2026-01-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Blanco,Negro,Azul', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_tax_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='talla',
            field=models.CharField(blank=True, help_text='S,M,L,XL', max_length=200),
        ),
    ]
