# Generated by Django 5.2.1 on 2026-01-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_detallefactura_imagen_url_alter_product_category_and_more'),
    ]

    operations = [
    ]
