# Generated by Django 5.2.1 on 2026-01-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_fix_missing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color_vinculado_new',
        ),
    ]
