# Generated by Django 5.2.1 on 2025-12-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_product_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colores',
            field=models.CharField(blank=True, help_text='Ejemplo: Blanco,Negro,Azul', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='tallas',
            field=models.CharField(blank=True, help_text='Ejemplo: 34,35,36,37,38,39,40', max_length=200),
        ),
    ]
